language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install coverage"
    - "pip install coveralls"
script:
    bash runtests.bash
after_success:
    coveralls --verbose
